# -*- coding: utf-8 -*-
"""GAN_image_generation_MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OWesReBHqCHK8e1YxTQPnU-ync9AoAX
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Generator Block
class Generator(nn.Module):
  def __init__(self, z_dim):
    super().__init__()
    self.model = nn.Sequential(
        nn.ConvTranspose2d(z_dim, 256, 7, 1, 0), # Input 1x1, Output 7x7
        nn.BatchNorm2d(256),
        nn.ReLU(),
        nn.ConvTranspose2d(256, 128, 4, 2, 1), # Input 7x7, Output 14x14
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.ConvTranspose2d(128, 1, 4, 2, 1), # Input 14x14, Output 28x28
        nn.Tanh(),
    )
  def forward(self, x):
      return self.model(x)

# Discriminator Block
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(1, 64, 4, 2, 1),
        nn.LeakyReLU(0.2),
        nn.Conv2d(64, 128, 4, 2, 1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(0.2),
        nn.Flatten(),
        nn.Linear(128*7*7, 1),
        nn.Sigmoid(),
    )

  def forward(self, x):
      return self.model(x)

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10



# Dataset loading
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Initializing loss function, generator, discriminator and optimizers
criterion = nn.BCELoss()
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)
optimizer_g = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_d = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 28, 28)

  fig, axes = plt.subplots(4, 4, figsize=(5, 5))
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()

# Training Step
for epoch in range(epochs):
  for real, _ in dataloader:
    real = real.to(device)
    batch_size = real.size(0)

    # Training discriminator
    noise = torch.randn(batch_size, z_dim, 1, 1).to(device)
    fake = generator(noise)

    real_labels = torch.ones(batch_size, 1).to(device)
    # Label Smoothing
    real_labels = torch.ones(batch_size, 1).to(device) * 0.9

    fake_labels = torch.zeros(batch_size, 1).to(device)

    # Real Loss
    D_real = discriminator(real)
    loss_real = criterion(D_real, real_labels)

    # Fake Loss
    D_fake = discriminator(fake.detach())
    loss_fake = criterion(D_fake, fake_labels)

    # Total Loss
    loss_D = loss_real + loss_fake

    optimizer_d.zero_grad()
    loss_D.backward()
    optimizer_d.step()

    # Train Discriminator
    output = discriminator(fake)
    g_loss = criterion(output, real_labels) # wants Discriminator to think fake is real

    optimizer_g.zero_grad()
    g_loss.backward()
    optimizer_g.step()
  show_images(real)
  show_images(fake)
  print(f"Epoch [{epoch}/{epochs}], Loss D: {loss_D.item()}, Loss G: {g_loss.item()}")

  
#Adapt the network architecture to generate higher resolution images than 28x28, perhaps by progressively increasing the output size or using more sophisticated upsmapling techniques.
class Generator(nn.Module):
    def __init__(self, z_dim):
        super().__init__()
        self.model = nn.Sequential(
            # Input: (z_dim, 1, 1) -> Output: (512, 4, 4)
            nn.ConvTranspose2d(z_dim, 512, 4, 1, 0, bias=False),
            nn.BatchNorm2d(512),
            nn.ReLU(True),
            # Input: (512, 4, 4) -> Output: (256, 8, 8)
            nn.ConvTranspose2d(512, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(True),
            # Input: (256, 8, 8) -> Output: (128, 16, 16)
            nn.ConvTranspose2d(256, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(True),
            # Input: (128, 16, 16) -> Output: (64, 32, 32)
            nn.ConvTranspose2d(128, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),
            # Input: (64, 32, 32) -> Output: (1, 64, 64)
            nn.ConvTranspose2d(64, 1, 4, 2, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            # Input: (1, 64, 64) -> Output: (64, 32, 32)
            nn.Conv2d(1, 64, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            # Input: (64, 32, 32) -> Output: (128, 16, 16)
            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),
            # Input: (128, 16, 16) -> Output: (256, 8, 8)
            nn.Conv2d(128, 256, 4, 2, 1, bias=False),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),
            # Input: (256, 8, 8) -> Output: (512, 4, 4)
            nn.Conv2d(256, 512, 4, 2, 1, bias=False),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),
            # Input: (512, 4, 4) -> Output: (1, 1, 1)
            nn.Conv2d(512, 1, 4, 1, 0, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x).view(-1, 1)

# Update show_images to handle 64x64 images
def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 64, 64) # Change to 64x64

  fig, axes = plt.subplots(4, 4, figsize=(8, 8)) # Increase figure size for better visualization
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()