# -*- coding: utf-8 -*-
"""demo1_middleware_observability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQsWZpmPrif90AZvv0GYzQqOgBhS2Y8o

# 🔬 Demo 1 — FastAPI Middleware & Observability
> **EY Backend Engineering Bootcamp — Day 9**

**Scenario:** You are an EY backend engineer on a global payments modernisation project. In this demo you will build and test the four middleware pillars — Logging, Metrics, Retry, and Circuit Breaker — that every production FastAPI service must have.

---
### Learning Objectives
- Attach HTTP middleware to a FastAPI app (logging + metrics)
- Use `structlog` for structured JSON logging with correlation IDs
- Expose a `/metrics` endpoint for Prometheus scraping
- Implement exponential-backoff retry with `tenacity`
- Implement a circuit breaker with `pybreaker`

### 🗺️ Road Map
```
Part 1 → Install deps
Part 2 → Logging middleware
Part 3 → Prometheus metrics middleware
Part 4 → Retry with tenacity
Part 5 → Circuit breaker with pybreaker
Part 6 → Run the full app (ngrok tunnel)
Extension Tasks →  Advanced challenges
```

## Part 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
#              prometheus-client prometheus-fastapi-instrumentator \
#              httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')

"""---
## Part 2 — Structured Logging Middleware

Every request must carry a **correlation ID** so you can trace a single payment across 50 microservices.
We attach middleware that:
1. Reads `X-Correlation-Id` from the incoming request (or generates a new UUID)
2. Logs request start / end as structured JSON
3. Passes the correlation ID forward in the response
"""

import structlog, logging, uuid, time
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')

"""---
## Part 3 — Prometheus Metrics Middleware

The four golden signals: **Latency, Traffic, Errors, Saturation**. We track all four with Prometheus counters and histograms.
"""

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST, CollectorRegistry
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# To handle re-running cells in Colab, we create a new registry each time.
# This prevents "Duplicated timeseries" errors.
# In a production app, you'd typically define metrics once globally.
metrics_registry = CollectorRegistry()

# Custom business metric: track payment amounts by currency
PAYMENT_AMOUNT = Histogram(
    'payment_amount_gbp', 'Payment amount in GBP',
    buckets=[10, 50, 100, 500, 1000, 5000, 10000],
    registry=metrics_registry # Assign to our new registry
)

ERROR_COUNT = Counter(
    'payment_errors_total', 'Total payment processing errors',
    ['error_type'],
    registry=metrics_registry # Assign to our new registry
)

# Auto-instrument all HTTP routes (latency, status codes, method)
# Ensure the Instrumentator uses our custom registry for its exposed metrics.
# Pass the registry to the Instrumentator constructor directly.
Instrumentator(registry=metrics_registry).instrument(app).expose(app)

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available (using custom registry)')
print('   → Tracking: request_count, request_latency, payment_amount')

"""---
## Part 4 — Retry Logic with Tenacity

Payment APIs are flaky under load. We use `tenacity` to retry failed calls with **exponential backoff + jitter** to avoid the thundering herd problem.
"""

import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ⚠️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('🔄 Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

"""---
## Part 5 — Circuit Breaker with PyBreaker

If a downstream service is consistently failing, retrying indefinitely makes things **worse**. The circuit breaker trips after `N` failures and returns a fast fallback for 30 seconds — preventing cascade failures.
"""

import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[LoggingListener()],
    name='fraud-api'
)

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

"""---
## Part 6 — Run the Full App

We start uvicorn in the background and expose it via a public ngrok tunnel so you can hit it from your browser or Postman.
"""

# ⚠️ You need a free ngrok account. Get your token at https://dashboard.ngrok.com
NGROK_TOKEN = 'PASTE_YOUR_TOKEN_HERE'  # ← replace this

import threading, uvicorn
from pyngrok import ngrok, conf

conf.get_default().auth_token = NGROK_TOKEN

def run_server():
    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='warning')

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(2)
tunnel = ngrok.connect(8000)
public_url = tunnel.public_url

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

"""---
## 🔥 Extension Tasks

### Extension A — Rate-Limiting Middleware *(Medium)*
Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
- Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
- Track limit hits as a Prometheus `Counter`

### Extension B — Correlation ID Propagation *(Medium)*
The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
- Add a `contextvars.ContextVar` to store the correlation ID per request
- Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
- Verify it appears in mock downstream requests

### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
- Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
- Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count

### Extension D — Structured Log Aggregation *(Advanced)*
- Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
- Configure `structlog` to write logs as newline-delimited JSON to a file
- Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`
"""

#Extension A
import structlog, logging, uuid, time
from collections import deque # New import for rate limiting
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Prometheus imports and registry (MOVED from wHihQkfnx3xZ)
from prometheus_client import Counter, Histogram, CollectorRegistry
# To handle re-running cells in Colab, we create a new registry each time.
# In a production app, you'd typically define metrics once globally.
metrics_registry = CollectorRegistry()

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        # Removed structlog.stdlib.add_logger_name as it's incompatible with PrintLoggerFactory
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

# --- Prometheus Metric for Rate Limit Hits (MOVED from GtzPA-xN0cMk) ---
RATE_LIMIT_HITS = Counter(
    'rate_limit_hits_total', 'Total number of times the rate limit was hit',
    ['client_ip'], # Label to track which IP hit the limit
    registry=metrics_registry
)

# --- In-memory storage for sliding window rate limiter (MOVED from GtzPA-xN0cMk) ---
# Dictionary to store request timestamps for each client IP
# Key: client_ip (str), Value: deque of timestamps (float)
RATE_LIMIT_WINDOW = 60 # seconds
RATE_LIMIT_MAX_REQUESTS = 100 # requests

client_requests = {}

@app.middleware('http') # RATE LIMITING MIDDLEWARE (MOVED from GtzPA-xN0cMk)
async def rate_limit_middleware(request: Request, call_next):
    client_ip = request.client.host

    # Initialize deque for the client if not present
    if client_ip not in client_requests:
        client_requests[client_ip] = deque()

    current_time = time.time()
    # Remove timestamps older than the window
    while client_requests[client_ip] and client_requests[client_ip][0] < current_time - RATE_LIMIT_WINDOW:
        client_requests[client_ip].popleft()

    # Check if the client has exceeded the request limit
    if len(client_requests[client_ip]) >= RATE_LIMIT_MAX_REQUESTS:
        # Increment Prometheus counter for rate limit hits
        RATE_LIMIT_HITS.labels(client_ip=client_ip).inc()

        # Calculate time until retry is possible
        time_since_oldest_request = current_time - client_requests[client_ip][0]
        retry_after = int(RATE_LIMIT_WINDOW - time_since_oldest_request)

        log.warning(
            'rate_limit.exceeded',
            client_ip=client_ip,
            requests_in_window=len(client_requests[client_ip]),
            limit=RATE_LIMIT_MAX_REQUESTS,
            window=RATE_LIMIT_WINDOW,
            retry_after=retry_after
        )
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            content={'detail': 'Rate limit exceeded'},
            headers={'Retry-After': str(retry_after)}
        )
    else:
        # Add current request timestamp
        client_requests[client_ip].append(current_time)

    response = await call_next(request)
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')
print(f'✅ Rate limiting middleware enabled ({RATE_LIMIT_MAX_REQUESTS} req/{RATE_LIMIT_WINDOW}s per IP)')


#Extension B
import structlog, logging, uuid, time
import contextvars # New import for context variable management
from collections import deque
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Prometheus imports and registry (MOVED from wHihQkfnx3xZ)
from prometheus_client import Counter, Histogram, CollectorRegistry
# To handle re-running cells in Colab, we create a new registry each time.
# In a production app, you'd typically define metrics once globally.
metrics_registry = CollectorRegistry()

# --- Context variable for Correlation ID ---
# This will store the correlation ID for the current request context
CORRELATION_ID = contextvars.ContextVar('correlation_id', default='unknown')

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        # Removed structlog.stdlib.add_logger_name as it's incompatible with PrintLoggerFactory
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))

    # Set the correlation ID in the context variable for this request
    token = CORRELATION_ID.set(correlation_id)

    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    try:
        response = await call_next(request)
    finally:
        # Ensure the context variable is reset after the request
        CORRELATION_ID.reset(token)

    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

# --- Prometheus Metric for Rate Limit Hits (MOVED from GtzPA-xN0cMk) ---
RATE_LIMIT_HITS = Counter(
    'rate_limit_hits_total', 'Total number of times the rate limit was hit',
    ['client_ip'], # Label to track which IP hit the limit
    registry=metrics_registry
)

# --- In-memory storage for sliding window rate limiter (MOVED from GtzPA-xN0cMk) ---
# Dictionary to store request timestamps for each client IP
# Key: client_ip (str), Value: deque of timestamps (float)
RATE_LIMIT_WINDOW = 60 # seconds
RATE_LIMIT_MAX_REQUESTS = 100 # requests

client_requests = {}

@app.middleware('http') # RATE LIMITING MIDDLEWARE (MOVED from GtzPA-xN0cMk)
async def rate_limit_middleware(request: Request, call_next):
    client_ip = request.client.host

    # Initialize deque for the client if not present
    if client_ip not in client_requests:
        client_requests[client_ip] = deque()

    current_time = time.time()
    # Remove timestamps older than the window
    while client_requests[client_ip] and client_requests[client_ip][0] < current_time - RATE_LIMIT_WINDOW:
        client_requests[client_ip].popleft()

    # Check if the client has exceeded the request limit
    if len(client_requests[client_ip]) >= RATE_LIMIT_MAX_REQUESTS:
        # Increment Prometheus counter for rate limit hits
        RATE_LIMIT_HITS.labels(client_ip=client_ip).inc()

        # Calculate time until retry is possible
        time_since_oldest_request = current_time - client_requests[client_ip][0]
        retry_after = int(RATE_LIMIT_WINDOW - time_since_oldest_request)

        log.warning(
            'rate_limit.exceeded',
            client_ip=client_ip,
            requests_in_window=len(client_requests[client_ip]),
            limit=RATE_LIMIT_MAX_REQUESTS,
            window=RATE_LIMIT_WINDOW,
            retry_after=retry_after
        )
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            content={'detail': 'Rate limit exceeded'},
            headers={'Retry-After': str(retry_after)}
        )
    else:
        # Add current request timestamp
        client_requests[client_ip].append(current_time)

    response = await call_next(request)
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'), correlation_id=CORRELATION_ID.get())
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')
print(f'✅ Rate limiting middleware enabled ({RATE_LIMIT_MAX_REQUESTS} req/{RATE_LIMIT_WINDOW}s per IP)')

import httpx # New import for making outbound HTTP requests
from httpx import Auth, Request as HttpxRequest, Response as HttpxResponse # Alias httpx.Request and Response to avoid conflict with fastapi.Request

# --- Custom httpx.Auth to inject Correlation ID ---
class CorrelationIdAuth(Auth):
    def auth_flow(self, request: HttpxRequest):
        # Get the correlation ID from the current context variable
        correlation_id = CORRELATION_ID.get()
        if correlation_id and correlation_id != 'unknown':
            request.headers['X-Correlation-Id'] = correlation_id
        yield request

print('✅ CorrelationIdAuth for httpx defined')

import httpx # Required for httpx.AsyncClient
from fastapi import Request # Explicitly import fastapi.Request here

client = httpx.AsyncClient(auth=CorrelationIdAuth())

@app.post('/payments/process')
async def process_payment(request: Request):
    body = await request.json()
    payment_id = str(uuid.uuid4())
    correlation_id = CORRELATION_ID.get()

    log.info('payment.processing.started', payment_id=payment_id, correlation_id=correlation_id)

    # Simulate calling a downstream service (e.g., fraud check, actual payment gateway)
    # The CorrelationIdAuth will automatically inject X-Correlation-Id here
    try:
        # For demonstration, we'll call a mock service that returns the headers it received
        mock_downstream_url = 'https://httpbin.org/headers'
        response = await client.post(mock_downstream_url, json={'payment_data': 'some_data'})
        downstream_headers = response.json().get('headers', {})
        received_correlation_id = downstream_headers.get('X-Correlation-Id')

        if received_correlation_id == correlation_id:
            log.info(
                'payment.processing.downstream_call.success',
                payment_id=payment_id,
                correlation_id=correlation_id,
                downstream_correlation_id=received_correlation_id,
                status='correlation_id_propagated'
            )
            return {'payment_id': payment_id, 'status': 'processed', 'correlation_id': received_correlation_id}
        else:
            log.error(
                'payment.processing.downstream_call.error',
                payment_id=payment_id,
                correlation_id=correlation_id,
                downstream_correlation_id=received_correlation_id,
                status='correlation_id_mismatch'
            )
            return JSONResponse(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                content={'detail': 'Correlation ID mismatch in downstream call'}
            )
    except httpx.RequestError as exc:
        log.error(
            'payment.processing.downstream_call.error',
            payment_id=payment_id,
            correlation_id=correlation_id,
            error=str(exc),
            status='downstream_service_unreachable'
        )
        return JSONResponse(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            content={'detail': f'Downstream service unreachable: {exc}'}
        )

print('✅ /payments/process endpoint added with Correlation ID propagation test')